using System.Text;

namespace E500Disassembler;

public sealed class DisassemblerOptions
{
    public bool GenerateLabels { get; init; } = true;
    public bool ShowAddresses { get; init; } = true;
    public bool ShowBytes { get; init; } = true;
    public string LabelPrefix { get; init; } = "L";
}

public sealed record DisassemblyResult(InputImage Image, IReadOnlyList<DecodedLine> Lines, string Source)
{
    public int InstructionCount => Lines.Count(x => !x.IsData && x.Mnemonic != "PRE");
    public int DataByteCount => Lines.Where(x => x.IsData).Sum(x => x.Bytes.Length);
}

public sealed class Disassembler
{
    public DisassemblyResult Disassemble(InputImage image, DisassemblerOptions? options = null, CancellationToken token = default)
    {
        options ??= new();
        if (string.IsNullOrWhiteSpace(options.LabelPrefix) || !char.IsLetter(options.LabelPrefix[0]) && options.LabelPrefix[0] != '_')
            throw new DisassemblyException("Label prefix must begin with a letter or underscore");

        var lines = new Decoder(image.Payload, image.Origin).Decode(token);
        var starts = lines.Select(x => x.Address).ToHashSet();
        var labels = options.GenerateLabels
            ? lines.Where(x => x.BranchTarget.HasValue && starts.Contains(x.BranchTarget.Value))
                .Select(x => x.BranchTarget!.Value).Distinct().Order().ToDictionary(x => x, x => $"{options.LabelPrefix}{x:X5}")
            : new Dictionary<int, string>();

        var source = new StringBuilder();
        source.AppendLine("; Generated by e500dasm for SHARP PC-E500 series / SC62015");
        source.AppendLine(image.Format == InputFormat.Ce140f
            ? $"; Input: CE-140F SAVE M, 16-byte header removed, {image.Payload.Length} payload bytes"
            : $"; Input: RAW, {image.Payload.Length} bytes");
        if (image.Format == InputFormat.Ce140f)
            source.AppendLine("; CE-140F header: " + Convert.ToHexString(image.Header, 0, image.Header.Length).Chunk(2).Select(x => new string(x)).Aggregate((a, b) => a + " " + b));
        source.AppendLine($"        ORG ${image.Origin:X5}");
        source.AppendLine();

        foreach (var line in lines)
        {
            token.ThrowIfCancellationRequested();
            if (labels.TryGetValue(line.Address, out string? label)) source.AppendLine(label + ":");
            string[] operands = (string[])line.Operands.Clone();
            if (line.BranchTarget.HasValue && labels.TryGetValue(line.BranchTarget.Value, out string? target)) operands = [target];
            string body = "        " + line.Mnemonic.PadRight(7) + string.Join(",", operands);
            var comments = new List<string>();
            if (options.ShowAddresses) comments.Add($"{line.Address:X5}");
            if (options.ShowBytes) comments.Add(string.Join(" ", line.Bytes.Select(x => x.ToString("X2"))));
            if (line.Note.Length != 0) comments.Add(line.Note);
            if (comments.Count != 0) body = body.PadRight(42) + (body.Length >= 42 ? " " : "") + "; " + string.Join(" | ", comments);
            source.AppendLine(body.TrimEnd());
        }
        source.AppendLine("        END");
        return new(image, lines, source.ToString());
    }

    public DisassemblyResult DisassembleFile(string path, InputFormat format, int? rawOrigin = null, DisassemblerOptions? options = null, CancellationToken token = default)
        => Disassemble(InputImage.ReadFile(path, format, rawOrigin), options, token);
}
