// ce140conv - Sharp CE-140F emulator file converter
// -----------------------------------------------------------------------------
// Converts between modern PC files and the files stored on the SD card of the
// Sharp_ce140f_emul (https://github.com/ffxx68/Sharp_ce140f_emul).
//
//   text2bas : PC text file  -> ASCII BASIC file          (loaded by  LOAD )
//   bas2text : ASCII BASIC file -> PC text file
//   bin2bas  : raw binary    -> binary/machine file        (loaded by  LOAD M)
//   bas2bin  : binary/machine file -> raw binary
//   info     : inspect a file stored for the emulator (ASCII vs binary, header)
//
// Design references (see ../Analysis and ../Sharp_ce140f_emul/commands.cpp):
//   * ASCII files are plain text lines. SAVE writes CR+LF line terminators and
//     LOAD reads a line up to 0x0D. End-of-file is signalled with 0x1A.
//   * A "binary" (non-ASCII) file is recognised by the emulator from its very
//     first byte being 0xFF. On the SD card such a file is:
//         [ 16-byte header generated by the pocket computer ] [ payload ]
//     Stripping the first 16 bytes yields the raw image; prepending a valid
//     16-byte header makes a raw image loadable with LOAD M.
//
// The header layout is CONFIRMED against real SAVE M captures taken from a
// PC-E650 (../Emulator/rom/S3A.ROM, S3B.ROM, CE2FULL.ROM, CE2RAW.ROM and
// GRAPHRAM.BIN - see buildHeader() below). Escape hatches remain available:
//   - bas2bin can save the real 16 bytes it strips  (--save-header hdr.bin)
//   - bin2bas can inject a real header file          (--header hdr.bin)
//   - info dumps and decodes the header of any binary file
//
// Standard C++17, single translation unit, no third-party dependencies.
// Optional Shift-JIS support on the PC-text side uses the Win32 API (_WIN32).
// -----------------------------------------------------------------------------

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <map>
#include <fstream>
#include <iostream>
#include <sstream>
#include <algorithm>

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX   // keep <windows.h> from defining min/max macros
#endif
#include <windows.h>
#endif

// ----------------------------------------------------------------------------
// small helpers
// ----------------------------------------------------------------------------
using Bytes = std::vector<uint8_t>;

static void die(const std::string& msg) {
    std::cerr << "ce140conv: error: " << msg << "\n";
    std::exit(2);
}

static Bytes readFile(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) die("cannot open input file: " + path);
    return Bytes((std::istreambuf_iterator<char>(f)),
                 std::istreambuf_iterator<char>());
}

static void writeFile(const std::string& path, const Bytes& data) {
    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    if (!f) die("cannot open output file: " + path);
    if (!data.empty())
        f.write(reinterpret_cast<const char*>(data.data()),
                static_cast<std::streamsize>(data.size()));
    if (!f) die("write failed: " + path);
}

// directory part of a path (including trailing separator), or "" if none
static std::string dirOf(const std::string& path) {
    size_t p = path.find_last_of("/\\");
    return (p == std::string::npos) ? std::string() : path.substr(0, p + 1);
}

// ----------------------------------------------------------------------------
// UTF-8 <-> Unicode code points
// ----------------------------------------------------------------------------
static std::vector<uint32_t> utf8ToCodepoints(const Bytes& in) {
    std::vector<uint32_t> out;
    size_t i = 0, n = in.size();
    // skip UTF-8 BOM
    if (n >= 3 && in[0] == 0xEF && in[1] == 0xBB && in[2] == 0xBF) i = 3;
    while (i < n) {
        uint32_t c = in[i];
        size_t extra;
        uint32_t cp;
        if (c < 0x80)       { cp = c;          extra = 0; }
        else if ((c >> 5) == 0x6) { cp = c & 0x1F; extra = 1; }
        else if ((c >> 4) == 0xE) { cp = c & 0x0F; extra = 2; }
        else if ((c >> 3) == 0x1E){ cp = c & 0x07; extra = 3; }
        else { cp = 0xFFFD; extra = 0; } // invalid lead byte
        if (i + extra >= n) { out.push_back(0xFFFD); break; }
        bool ok = true;
        for (size_t k = 1; k <= extra; k++) {
            uint8_t cc = in[i + k];
            if ((cc >> 6) != 0x2) { ok = false; break; }
            cp = (cp << 6) | (cc & 0x3F);
        }
        if (!ok) { out.push_back(0xFFFD); i++; continue; }
        out.push_back(cp);
        i += extra + 1;
    }
    return out;
}

static void appendUtf8(Bytes& out, uint32_t cp) {
    if (cp < 0x80) {
        out.push_back(static_cast<uint8_t>(cp));
    } else if (cp < 0x800) {
        out.push_back(static_cast<uint8_t>(0xC0 | (cp >> 6)));
        out.push_back(static_cast<uint8_t>(0x80 | (cp & 0x3F)));
    } else if (cp < 0x10000) {
        out.push_back(static_cast<uint8_t>(0xE0 | (cp >> 12)));
        out.push_back(static_cast<uint8_t>(0x80 | ((cp >> 6) & 0x3F)));
        out.push_back(static_cast<uint8_t>(0x80 | (cp & 0x3F)));
    } else {
        out.push_back(static_cast<uint8_t>(0xF0 | (cp >> 18)));
        out.push_back(static_cast<uint8_t>(0x80 | ((cp >> 12) & 0x3F)));
        out.push_back(static_cast<uint8_t>(0x80 | ((cp >> 6) & 0x3F)));
        out.push_back(static_cast<uint8_t>(0x80 | (cp & 0x3F)));
    }
}

#ifdef _WIN32
// Shift-JIS (CP932) <-> Unicode code points, Windows only
static std::vector<uint32_t> sjisToCodepoints(const Bytes& in) {
    std::vector<uint32_t> out;
    if (in.empty()) return out;
    int wn = MultiByteToWideChar(932, 0, reinterpret_cast<const char*>(in.data()),
                                 (int)in.size(), nullptr, 0);
    std::wstring w(wn, L'\0');
    MultiByteToWideChar(932, 0, reinterpret_cast<const char*>(in.data()),
                        (int)in.size(), &w[0], wn);
    for (size_t i = 0; i < w.size(); i++) {
        uint32_t cp = (uint16_t)w[i];
        if (cp >= 0xD800 && cp <= 0xDBFF && i + 1 < w.size()) {
            uint32_t lo = (uint16_t)w[i + 1];
            cp = 0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00);
            i++;
        }
        out.push_back(cp);
    }
    return out;
}
static Bytes codepointsToSjis(const std::vector<uint32_t>& cps) {
    std::wstring w;
    for (uint32_t cp : cps) {
        if (cp < 0x10000) w.push_back((wchar_t)cp);
        else {
            cp -= 0x10000;
            w.push_back((wchar_t)(0xD800 + (cp >> 10)));
            w.push_back((wchar_t)(0xDC00 + (cp & 0x3FF)));
        }
    }
    int n = WideCharToMultiByte(932, 0, w.c_str(), (int)w.size(),
                                nullptr, 0, nullptr, nullptr);
    Bytes out(n);
    if (n) WideCharToMultiByte(932, 0, w.c_str(), (int)w.size(),
                               reinterpret_cast<char*>(out.data()), n,
                               nullptr, nullptr);
    return out;
}
#endif

// ----------------------------------------------------------------------------
// Sharp character set  <->  Unicode code point
//
// Bytes not covered by the loaded table round-trip losslessly through the
// Unicode Private Use Area: Sharp byte 0xHH  <->  U+E000+HH. This guarantees a
// byte-perfect bas2text -> text2bas round trip even for glyphs we have not yet
// mapped, while still letting you read the parts we have.
// ----------------------------------------------------------------------------
static const uint32_t PUA_BASE = 0xE000;

struct Charset {
    uint32_t toUni[256];              // Sharp byte -> code point
    std::map<uint32_t, uint8_t> toSharp; // code point -> Sharp byte

    void buildDefault() {
        for (int b = 0; b < 256; b++) toUni[b] = PUA_BASE + b; // unknown -> PUA
        // printable ASCII is identity
        for (int b = 0x20; b <= 0x7E; b++) map((uint8_t)b, (uint32_t)b);
        // whitespace / control we care about
        map(0x09, 0x09); // TAB
        map(0x0A, 0x0A); // LF
        map(0x0D, 0x0D); // CR
        rebuildReverse();
    }
    void map(uint8_t b, uint32_t cp) { toUni[b] = cp; }
    void rebuildReverse() {
        toSharp.clear();
        for (int b = 0; b < 256; b++) {
            uint32_t cp = toUni[b];
            // first definition wins for a given code point
            if (toSharp.find(cp) == toSharp.end())
                toSharp[cp] = (uint8_t)b;
        }
    }

    // Load / override entries from a .tab file. Lines:
    //   HH  U+XXXX      ; comment      (map Sharp byte HH to code point XXXX)
    //   HH  =           ; explicitly undefined -> keep PUA fallback
    // '#' or ';' starts a comment. Blank lines ignored.
    bool loadFile(const std::string& path, std::string* err) {
        std::ifstream f(path);
        if (!f) { if (err) *err = "cannot open charset file: " + path; return false; }
        std::string line;
        int lineno = 0;
        while (std::getline(f, line)) {
            lineno++;
            // strip comments
            size_t c = line.find_first_of("#;");
            if (c != std::string::npos) line = line.substr(0, c);
            std::istringstream ls(line);
            std::string tokB, tokU;
            if (!(ls >> tokB)) continue; // blank
            unsigned b;
            if (sscanf(tokB.c_str(), "%x", &b) != 1 || b > 0xFF) {
                if (err) *err = path + ":" + std::to_string(lineno) + ": bad byte token";
                return false;
            }
            if (!(ls >> tokU)) continue; // byte with no mapping -> ignore
            if (tokU == "=") { toUni[b] = PUA_BASE + b; continue; }
            unsigned cp;
            const char* s = tokU.c_str();
            if (s[0] == 'U' && s[1] == '+') s += 2;
            else if (s[0] == '0' && (s[1] == 'x' || s[1] == 'X')) s += 2;
            if (sscanf(s, "%x", &cp) != 1) {
                if (err) *err = path + ":" + std::to_string(lineno) + ": bad code point token";
                return false;
            }
            toUni[b] = cp;
        }
        rebuildReverse();
        return true;
    }
};

// ----------------------------------------------------------------------------
// 16-byte binary-file header  (layout confirmed on real PC-E650 SAVE M files)
// ----------------------------------------------------------------------------
//   off  0..3  FF 00 06 01   file type: machine code   (constant)
//   off  4     10                                      (constant)
//   off  5..7  length,        24-bit little endian
//   off  8..10 start address, 24-bit little endian
//   off 11..13 FF FF FF                                (constant)
//   off 14..15 00 0F                                   (constant)
// Only the length and the start address vary; the other 11 bytes were identical
// in every captured file. Example (S3A.ROM, 0x40000 bytes loaded at 0xC0000):
//   ff 00 06 01 10 00 00 04 00 00 0c ff ff ff 00 0f
static const size_t HDR_LEN = 16;

// The constant bytes, at their offsets in the header.
static const uint8_t HDR_SIG[5]  = { 0xFF, 0x00, 0x06, 0x01, 0x10 };  // off 0..4
static const uint8_t HDR_TAIL[5] = { 0xFF, 0xFF, 0xFF, 0x00, 0x0F };  // off 11..15

static void put24le(Bytes& h, size_t at, uint32_t v) {
    h[at]     = (uint8_t)( v        & 0xFF);
    h[at + 1] = (uint8_t)((v >> 8)  & 0xFF);
    h[at + 2] = (uint8_t)((v >> 16) & 0xFF);
}

static uint32_t get24le(const Bytes& h, size_t at) {
    return (uint32_t)h[at] | ((uint32_t)h[at + 1] << 8) | ((uint32_t)h[at + 2] << 16);
}

// Build the 16-byte header for a raw image of the given start address and length.
static Bytes buildHeader(uint32_t addr, uint32_t length) {
    Bytes h(HDR_LEN, 0x00);
    std::memcpy(&h[0],  HDR_SIG,  sizeof(HDR_SIG));    // off  0..4
    put24le(h, 5,  length);                            // off  5..7
    put24le(h, 8,  addr);                              // off  8..10
    std::memcpy(&h[11], HDR_TAIL, sizeof(HDR_TAIL));   // off 11..15
    return h;
}

// ----------------------------------------------------------------------------
// conversions
// ----------------------------------------------------------------------------
struct Options {
    bool sjis        = false;   // treat PC text as Shift-JIS (CP932) instead of UTF-8
    bool sharpCR     = false;   // Sharp line terminator: CR only (default CR+LF)
    bool noEof       = false;   // do not append 0x1A EOF marker
    bool hostLF      = false;   // bas2text: output LF only (default CR+LF)
    bool asciiOnly   = false;   // ignore charset table, ASCII identity only
    uint32_t addr    = 0;       // bin2bas load address
    bool haveAddr    = false;
    std::string headerFile;     // bin2bas: inject this 16-byte header
    std::string saveHeader;     // bas2bin: write the stripped header here
    std::string charsetFile;    // explicit charset table path
};

static std::vector<uint32_t> decodePcText(const Bytes& in, const Options& o) {
#ifdef _WIN32
    if (o.sjis) return sjisToCodepoints(in);
#else
    if (o.sjis) die("Shift-JIS (--sjis) is only supported on the Windows build");
#endif
    return utf8ToCodepoints(in);
}

static Bytes encodePcText(const std::vector<uint32_t>& cps, const Options& o) {
#ifdef _WIN32
    if (o.sjis) return codepointsToSjis(cps);
#else
    if (o.sjis) die("Shift-JIS (--sjis) is only supported on the Windows build");
#endif
    Bytes out;
    for (uint32_t cp : cps) appendUtf8(out, cp);
    return out;
}

static int text2bas(const std::string& in, const std::string& out,
                    const Charset& cs, const Options& o) {
    Bytes raw = readFile(in);
    std::vector<uint32_t> cps = decodePcText(raw, o);

    Bytes result;
    size_t warnUnmapped = 0;
    for (size_t i = 0; i < cps.size(); i++) {
        uint32_t cp = cps[i];
        // normalise any of CRLF / CR / LF into the Sharp line terminator
        if (cp == 0x0D || cp == 0x0A) {
            if (cp == 0x0D && i + 1 < cps.size() && cps[i + 1] == 0x0A) i++; // eat CRLF pair
            result.push_back(0x0D);
            if (!o.sharpCR) result.push_back(0x0A);
            continue;
        }
        uint8_t b;
        if (o.asciiOnly) {
            if (cp <= 0x7F) b = (uint8_t)cp;
            else { b = '?'; warnUnmapped++; }
        } else if (cp >= PUA_BASE && cp <= PUA_BASE + 0xFF) {
            b = (uint8_t)(cp - PUA_BASE);               // PUA passthrough
        } else {
            auto it = cs.toSharp.find(cp);
            if (it != cs.toSharp.end()) b = it->second;
            else { b = '?'; warnUnmapped++; }
        }
        result.push_back(b);
    }
    if (!o.noEof) result.push_back(0x1A); // end-of-file marker

    writeFile(out, result);
    if (warnUnmapped)
        std::cerr << "ce140conv: warning: " << warnUnmapped
                  << " character(s) had no Sharp mapping and became '?'\n";
    std::cerr << "text2bas: wrote " << result.size() << " bytes to " << out << "\n";
    return 0;
}

static int bas2text(const std::string& in, const std::string& out,
                    const Charset& cs, const Options& o) {
    Bytes raw = readFile(in);
    if (!raw.empty() && raw[0] == 0xFF)
        std::cerr << "ce140conv: warning: input starts with 0xFF (looks like a "
                     "binary/LOAD M file). Did you mean bas2bin?\n";

    // drop a trailing EOF marker if present
    if (!raw.empty() && raw.back() == 0x1A) raw.pop_back();

    std::vector<uint32_t> cps;
    for (size_t i = 0; i < raw.size(); i++) {
        uint8_t b = raw[i];
        if (b == 0x0D) {
            if (i + 1 < raw.size() && raw[i + 1] == 0x0A) i++; // eat CRLF pair
            cps.push_back(o.hostLF ? 0x0A : 0x0D);
            if (!o.hostLF) cps.push_back(0x0A);
            continue;
        }
        if (b == 0x0A) { // lone LF
            cps.push_back(o.hostLF ? 0x0A : 0x0D);
            if (!o.hostLF) cps.push_back(0x0A);
            continue;
        }
        cps.push_back(o.asciiOnly ? (uint32_t)b : cs.toUni[b]);
    }

    Bytes result = encodePcText(cps, o);
    writeFile(out, result);
    std::cerr << "bas2text: wrote " << result.size() << " bytes to " << out << "\n";
    return 0;
}

static int bin2bas(const std::string& in, const std::string& out,
                   const Options& o) {
    Bytes payload = readFile(in);
    Bytes header;
    if (!o.headerFile.empty()) {
        header = readFile(o.headerFile);
        if (header.size() != HDR_LEN)
            die("--header file must be exactly " + std::to_string(HDR_LEN) +
                " bytes (got " + std::to_string(header.size()) + ")");
        if (header[0] != 0xFF)
            std::cerr << "ce140conv: warning: --header byte 0 is not 0xFF; the "
                         "emulator identifies binary files by a leading 0xFF\n";
    } else {
        uint32_t addr = o.haveAddr ? o.addr : 0;
        if (!o.haveAddr)
            std::cerr << "ce140conv: warning: no --addr given, using 0. Provide "
                         "the real load address for a correct LOAD M header.\n";
        if (addr > 0xFFFFFF)
            die("--addr does not fit in the 24-bit address field");
        if (payload.size() > 0xFFFFFF)
            die("payload is larger than the 24-bit length field (16777215 bytes)");
        header = buildHeader(addr, (uint32_t)payload.size());
    }
    Bytes result;
    result.reserve(header.size() + payload.size());
    result.insert(result.end(), header.begin(), header.end());
    result.insert(result.end(), payload.begin(), payload.end());
    writeFile(out, result);
    std::cerr << "bin2bas: wrote " << result.size() << " bytes ("
              << HDR_LEN << "-byte header + " << payload.size()
              << " payload) to " << out << "\n";
    return 0;
}

static int bas2bin(const std::string& in, const std::string& out,
                   const Options& o) {
    Bytes raw = readFile(in);
    if (raw.size() < HDR_LEN)
        die("input is shorter than a " + std::to_string(HDR_LEN) + "-byte header");
    if (raw[0] != 0xFF)
        std::cerr << "ce140conv: warning: input does not start with 0xFF; it may "
                     "be an ASCII file, not a binary/LOAD M file.\n";

    Bytes header(raw.begin(), raw.begin() + HDR_LEN);
    Bytes payload(raw.begin() + HDR_LEN, raw.end());

    if (!o.saveHeader.empty()) {
        writeFile(o.saveHeader, header);
        std::cerr << "bas2bin: saved " << HDR_LEN << "-byte header to "
                  << o.saveHeader << "\n";
    }
    writeFile(out, payload);
    std::cerr << "bas2bin: wrote " << payload.size()
              << " bytes (header stripped) to " << out << "\n";
    return 0;
}

static void hexDump(const Bytes& d, size_t count) {
    size_t n = std::min(count, d.size());
    for (size_t i = 0; i < n; i += 16) {
        char buf[8];
        std::snprintf(buf, sizeof(buf), "%04zx  ", i);
        std::cout << buf;
        for (size_t j = 0; j < 16; j++) {
            if (i + j < n) { std::snprintf(buf, sizeof(buf), "%02x ", d[i + j]); std::cout << buf; }
            else std::cout << "   ";
        }
        std::cout << " ";
        for (size_t j = 0; j < 16 && i + j < n; j++) {
            uint8_t b = d[i + j];
            std::cout << (char)((b >= 0x20 && b < 0x7F) ? b : '.');
        }
        std::cout << "\n";
    }
}

static int info(const std::string& in) {
    Bytes raw = readFile(in);
    std::cout << "file       : " << in << "\n";
    std::cout << "size       : " << raw.size() << " bytes\n";
    if (raw.empty()) { std::cout << "type       : (empty)\n"; return 0; }
    bool binary = raw[0] == 0xFF;
    std::cout << "first byte : 0x" << std::hex << (int)raw[0] << std::dec << "\n";
    std::cout << "type       : " << (binary ? "BINARY (LOAD M) - has 16-byte header"
                                            : "ASCII  (LOAD)") << "\n";
    if (binary) {
        size_t payload = raw.size() >= HDR_LEN ? raw.size() - HDR_LEN : 0;
        std::cout << "payload    : " << payload << " bytes (after "
                  << HDR_LEN << "-byte header)\n";
        std::cout << "header hex :\n";
        hexDump(Bytes(raw.begin(), raw.begin() + std::min(raw.size(), HDR_LEN)), HDR_LEN);
        if (raw.size() >= HDR_LEN) {
            Bytes h(raw.begin(), raw.begin() + HDR_LEN);
            uint32_t length = get24le(h, 5);
            uint32_t addr   = get24le(h, 8);
            char buf[64];
            std::snprintf(buf, sizeof(buf), "0x%06X (%u bytes)", length, length);
            std::cout << "length     : " << buf << "\n";
            std::snprintf(buf, sizeof(buf), "0x%05X-0x%05X", addr,
                          (unsigned)(addr + (payload ? payload - 1 : 0)));
            std::cout << "address    : " << buf << "\n";
            if (std::memcmp(&h[0], HDR_SIG, sizeof(HDR_SIG)) != 0 ||
                std::memcmp(&h[11], HDR_TAIL, sizeof(HDR_TAIL)) != 0)
                std::cout << "note       : constant header bytes differ from the "
                             "known SAVE M signature\n";
            if (length != payload)
                std::cout << "note       : header length and actual payload size "
                             "disagree\n";
        }
    } else {
        bool eof = raw.back() == 0x1A;
        std::cout << "eof marker : " << (eof ? "yes (0x1A)" : "no") << "\n";
        std::cout << "head hex   :\n";
        hexDump(raw, 64);
    }
    return 0;
}

// ----------------------------------------------------------------------------
// CLI
// ----------------------------------------------------------------------------
static void usage() {
    std::cout <<
"ce140conv - Sharp CE-140F emulator file converter\n"
"\n"
"Usage:\n"
"  ce140conv text2bas <in.txt> <out.bas> [options]   PC text  -> ASCII (LOAD)\n"
"  ce140conv bas2text <in.bas> <out.txt> [options]   ASCII    -> PC text\n"
"  ce140conv bin2bas  <in.bin> <out.bas> [options]   raw bin  -> binary (LOAD M)\n"
"  ce140conv bas2bin  <in.bas> <out.bin> [options]   binary   -> raw bin\n"
"  ce140conv info     <file>                          inspect a stored file\n"
"\n"
"Text options:\n"
"  --sjis            PC text is Shift-JIS (CP932) instead of UTF-8 (Windows)\n"
"  --cr              Sharp line terminator = CR only (default CR+LF)\n"
"  --no-eof          do not append the 0x1A end-of-file marker (text2bas)\n"
"  --lf              output LF line endings (bas2text; default CR+LF)\n"
"  --ascii           ignore the charset table, map ASCII only\n"
"  --charset <file>  use this Sharp charset table (default: charset_e500.tab\n"
"                    next to the exe or in the current directory)\n"
"\n"
"Binary options:\n"
"  --addr <n>        load address for bin2bas (e.g. --addr 0xB0000)\n"
"  --header <file>   inject this exact 16-byte header (bin2bas)\n"
"  --save-header <f> save the stripped 16-byte header (bas2bin)\n";
}

static uint32_t parseUint(const std::string& s) {
    uint32_t v = 0;
    const char* p = s.c_str();
    if ((p[0] == '0' && (p[1] == 'x' || p[1] == 'X')) || p[0] == '$') {
        p += (p[0] == '$') ? 1 : 2;
        if (sscanf(p, "%x", &v) != 1) die("bad number: " + s);
    } else if (p[0] == '&' && (p[1] == 'H' || p[1] == 'h')) {
        if (sscanf(p + 2, "%x", &v) != 1) die("bad number: " + s);
    } else {
        if (sscanf(p, "%u", &v) != 1) die("bad number: " + s);
    }
    return v;
}

int main(int argc, char** argv) {
    if (argc < 2) { usage(); return 1; }
    std::string cmd = argv[1];
    if (cmd == "-h" || cmd == "--help" || cmd == "help") { usage(); return 0; }

    // collect positionals and options
    std::vector<std::string> pos;
    Options o;
    for (int i = 2; i < argc; i++) {
        std::string a = argv[i];
        auto need = [&](const char* name) -> std::string {
            if (i + 1 >= argc) die(std::string("missing value for ") + name);
            return argv[++i];
        };
        if      (a == "--sjis")   o.sjis = true;
        else if (a == "--cr")     o.sharpCR = true;
        else if (a == "--no-eof") o.noEof = true;
        else if (a == "--lf")     o.hostLF = true;
        else if (a == "--ascii")  o.asciiOnly = true;
        else if (a == "--addr")   { o.addr = parseUint(need("--addr")); o.haveAddr = true; }
        else if (a == "--header") o.headerFile = need("--header");
        else if (a == "--save-header") o.saveHeader = need("--save-header");
        else if (a == "--charset") o.charsetFile = need("--charset");
        else if (!a.empty() && a[0] == '-') die("unknown option: " + a);
        else pos.push_back(a);
    }

    // load charset for text modes
    Charset cs;
    cs.buildDefault();
    if (!o.asciiOnly && (cmd == "text2bas" || cmd == "bas2text")) {
        std::string path = o.charsetFile;
        if (path.empty()) {
            // try next to the exe, then current dir
            std::string exeDir = dirOf(argv[0]);
            std::string cand1 = exeDir + "charset_e500.tab";
            std::ifstream t1(cand1);
            if (t1) path = cand1;
            else {
                std::ifstream t2("charset_e500.tab");
                if (t2) path = "charset_e500.tab";
            }
        }
        if (!path.empty()) {
            std::string err;
            if (!cs.loadFile(path, &err)) die(err);
            std::cerr << "ce140conv: using charset table " << path << "\n";
        } else if (o.charsetFile.empty()) {
            std::cerr << "ce140conv: note: no charset_e500.tab found; using "
                         "built-in ASCII + PUA fallback only\n";
        }
    }

    auto needPos = [&](size_t n) {
        if (pos.size() < n) { usage(); die("missing file argument(s)"); }
    };

    if (cmd == "text2bas") { needPos(2); return text2bas(pos[0], pos[1], cs, o); }
    if (cmd == "bas2text") { needPos(2); return bas2text(pos[0], pos[1], cs, o); }
    if (cmd == "bin2bas")  { needPos(2); return bin2bas(pos[0], pos[1], o); }
    if (cmd == "bas2bin")  { needPos(2); return bas2bin(pos[0], pos[1], o); }
    if (cmd == "info")     { needPos(1); return info(pos[0]); }

    usage();
    die("unknown command: " + cmd);
    return 2;
}
